name: preview
description: Create samples of your Flutter widgets and preview them in real time
version: 0.0.8
repository: https://github.com/jamesblasco/flutter_preview/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  path: ">=0.9.0 <2.0.0" 
  analyzer: '>=0.35.0 <0.40.0'
  args: ">=1.4.0 <2.0.0"
  vm_service: '>=3.0.0 <5.0.0'
  async: ^2.3.0
  http: ^0.12.0
  dart_style: ^1.3.4
  device_frame: ^0.1.0
  json_rpc_2: ^2.2.1
  web_socket_channel: ^1.1.0
  stream_channel: ^2.0.0
  shelf: ^0.7.7
  shelf_router: ^0.7.2
  shelf_web_socket: ^0.2.3
  shelf_static: ^0.2.8
  http_server: ^0.9.8+3
  mime: ^0.9.6+3
  http_parser: ^3.1.4
 
#  window_size: 
#   path: ./plugins/window_size/

dev_dependencies:
  flutter_test:
    sdk: flutter
    



    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: PreviewIcons
      fonts:
        - asset: assets/PreviewIcons.ttf
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
 

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
